### ISSUE TITLE
Kijk eens naar ```<ol>``` in plaats van ```ul``` :)

### ISSUE THREAD

**Issue by itsValyria** [vsheo/all-human-accessible-website#3]
Hey!

Ik zat net door jouw code te kijken en het viel me op dat je best wat ```<ul>``` elements gebruikt, voor lijsten die je denk ik in de volgorde wil weergeven die je ook in je HTML hebt staan. Misschien is het het waard om je te verdiepen in het ```<ol>``` element, en te kijken of dit niet beter past.

### Voorbeeld
https://github.com/vsheo/all-human-accessible-website/blob/d4f11a22995cb36e05d4fd8aea368845bbc6f07f/index.html#L20-L28

[Hier](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/ol#usage_notes) kun je wat meer lezen over het ```<ol>``` element. MDN docs to the rescue! :D

<img src="https://media2.giphy.com/media/HZrx8kjIA7lyeTqXVM/giphy.gif"/>

**Comment by vsheo** [comment]
Dank je wel voor het advies,
ik heb de ul nu tot ol gemaakt.
