### ISSUE TITLE
Code/Design Review Toegankelijkheid

### ISSUE THREAD

**Issue by irisvw** [vsheo/all-human-accessible-website#4]
- HTML validator geeft vier errors: image elements mogen geen lege src hebben. (regel 59, 70, 127 & 138)
- Voor dagen van de week en tijden, waar de volgorde uitmaakt, kun je misschien beter een `<ol>` gebruiken in plaats van een `<ul>`.
- Niet relevant voor de toegankelijkheid, maar het zou fijn zijn om je code wat ademruimte te geven. https://github.com/fdnd-task/the-client-website/blob/main/docs/code-conventies.md#geef-je-html-ademruimte
- De alt tekst voor de afbeeldingen zou misschien iets uitgebreider of beschrijvender kunnen.

**Comment by vsheo** [comment]
dank je wel voor de review,
de images hebben nu allemaal een src,
ik heb de ul tot een ol gemaakt,
en ik heb betere alt teksten gegeven aan mijn images.
