### ISSUE TITLE
Code Design Review Toegankelijkheid | 18/10/2024 | Door Karima Mouadi en Robin Wouterson

### ISSUE THREAD

**Issue by Robinwouterson** [vsheo/all-human-accessible-website#5]
We hebben je website laten testen door een HTML validator en de volgende punten kwamen naar voren:

-> De `<src>`  tag mag niet leeg staan (check screenshot hieronder)

![Screenshot 2024-10-18 111209](https://github.com/user-attachments/assets/af8a8cd2-086f-44c1-a4a0-38d8a93be035)

Verder hebben we na het doorlopen van de volledige checklist kunnen concluderen dat de website aan de gestelde eisen voldoet. 

Je code en website zien er goed uit. Keep it up!

Code review door @karima002 en @Robinwouterson.

**Comment by vsheo** [comment]
Dank je wel voor de review,
Het probleem is nu opgelost.
