### ISSUE TITLE
Code/design Review

### ISSUE THREAD

**Issue by halie404** [vsheo/all-human-accessible-website#6]
Je responsiveness ziet er goed uit en je schema van de programmas zijn ook heel duidelijk. 
Hieronder wat kleine puntjes: 

1. Je image src is leeg let daarop.

https://github.com/vsheo/all-human-accessible-website/blob/d4f11a22995cb36e05d4fd8aea368845bbc6f07f/index.html#L59
https://github.com/vsheo/all-human-accessible-website/blob/d4f11a22995cb36e05d4fd8aea368845bbc6f07f/index.html#L70
https://github.com/vsheo/all-human-accessible-website/blob/d4f11a22995cb36e05d4fd8aea368845bbc6f07f/index.html#L127

2. Misschien i.pv. een detail die uitklapt zou je misschien de informatie gelijk kunnen tonen dat is wat duidelijker voor de user: 

https://github.com/vsheo/all-human-accessible-website/blob/d4f11a22995cb36e05d4fd8aea368845bbc6f07f/index.html#L14-L19

**Comment by vsheo** [comment]
de images hebben nu allemaal src.
ik heb het ook wat duidelijker gemaakt dat er op de details geklikt kan worden
